# Generated by Django 4.0.6 on 2022-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(blank=True, max_length=100)),
                ('title_2', models.CharField(blank=True, max_length=100)),
                ('news1', models.CharField(blank=True, max_length=100)),
                ('news1_title', models.CharField(blank=True, max_length=100)),
                ('news1_about', models.TextField(blank=True, max_length=500)),
                ('news2', models.CharField(blank=True, max_length=100)),
                ('news2_title', models.CharField(blank=True, max_length=100)),
                ('news2_about', models.TextField(blank=True, max_length=500)),
                ('news3', models.CharField(blank=True, max_length=100)),
                ('news3_title', models.CharField(blank=True, max_length=100)),
                ('news3_about', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
