# Generated by Django 4.0.6 on 2022-07-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('categories', models.CharField(blank=True, max_length=100)),
                ('product_image', models.ImageField(blank=True, default='', upload_to='portfolio')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('product_date_added', models.DateField(auto_now=True)),
                ('product_about', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('categories', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('product_price', models.IntegerField(blank=True)),
                ('product_about', models.TextField(blank=True, max_length=300)),
                ('product_image', models.ImageField(blank=True, default='', upload_to='portfolio')),
            ],
        ),
    ]
