# Generated by Django 4.0.6 on 2022-07-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_main_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, default='', upload_to='portfolio')),
                ('video', models.FileField(null=True, upload_to='video')),
            ],
        ),
    ]
