# Generated by Django 4.0.6 on 2022-07-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
