# Generated by Django 4.0.6 on 2022-07-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_news1_news_news_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
